# NAME: Bradley Mont
# EMAIL: bradleymont@gmail.com
# ID: 804993030

CC = gcc
CFLAGS = -Wall -Wextra -g -lm -lmraa

default:
	$(CC) $(CFLAGS) lab4b.c -o lab4b
check:
	
clean:
	rm -f lab4b *.tar.gz *.o
dist:
	tar -czf lab4b-804993030.tar.gz lab4b.c Makefile README
