# NAME: Bradley Mont
# EMAIL: bradleymont@gmail.com
# ID: 804993030

default:
	cp lab3b.py lab3b
	chmod +x lab3b.py lab3b
dist:
	tar -czf lab3b-804993030.tar.gz lab3b.py Makefile README
clean:
	rm -f lab3b *.tar.gz *.o
